### ISSUE TITLE
Tying in input fields

### ISSUE THREAD

**Issue by Rossco1991** [4GeeksAcademy/Wish-or-Junk-Final-Project#52]
Integrate input fields for post so posts can be created and data called back when completed

**Comment by UsuallyAwakeGuy** [comment]
I've fixed multiple bugs in the postModal.js file. These bugs were preventing the ability to use the modal form fields and buttons properly and submit using the assigned button. Additionally I changed the dismissal behavior to not trigger when clicking on the background of the site. Instead, you must click either of the Close buttons. These changes have been committed to the branch, but not yet merged with origin.

I'm moving this task back to "Todo" because I'm still traveling and am unsure when I'll be able to carry it further. If someone else is able to pick it up from here, it would be good. If not, I'll get to it as soon as I can manage.
